name: Test suite

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8, pypy2, pypy3]
        env: [TOXENV=py]
        include:
        - name: Flake8
          python: 3.7
          env: TOXENV=flake8
        - name: Pylint
          python: 3.7
          env: TOXENV=pylint
        - name: PyPI description
          python: 3.7
          env: TOXENV=readme

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox
      run: pip install tox
    - name: Run tox
      run: tox
